apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: default
spec:
  containers:
  - name: alpine-container
    image: alpine/git:latest
    command: ["/bin/sh", "-c", "apk add apache2-utils vim && sleep 36000"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Never