apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-load-generator
  namespace: default # 確保與 ConfigMap 位於相同 Namespace
spec:
  replicas: 1 # 初始 Pod 數量，請根據你的總 RPS 目標和單 Pod 能力調整
  selector:
    matchLabels:
      app: dns-load-generator
      test-target: dns
  template:
    metadata:
      labels:
        app: dns-load-generator
        test-target: dns
    spec:
      containers:
      - name: k6
        image: grafana/k6:latest # 使用 k6 官方 Docker 映像檔
        command: ["k6"]
        args:
          - "run"
          - "--dns"
          - "ttl=0"
          - "/etc/k6/load-test.js"
        env:
        - name: TEST_MODE
          value: "dns_mode" # 告知腳本這是 dns 測試模式
        - name: TARGET_HOST
          value: "nginx-lb-internal.test-audit.com" # ***替換成你的內部 LB dns***
        - name: TARGET_PORT
          value: "80" # 根據你的服務端口調整
        - name: API_PATH
          value: "/" # 根據你的服務 API 路徑調整
        volumeMounts:
        - name: k6-script-volume
          mountPath: /etc/k6 # 將 ConfigMap 掛載到此路徑
      volumes:
      - name: k6-script-volume
        configMap:
          name: k6-test-script # 引用上面定義的 ConfigMap