scrape_configs:
  - job_name: 'kube-dns-nodelocaldns-nodelocaldns'
    static_configs:
      - targets: ['host.docker.internal:9001']
  - job_name: 'kube-dns-nodelocaldns-kube-dns'
    static_configs:
      - targets: ['host.docker.internal:9002']